---

nginx:
    image: abaco/nginx$TAG
    volumes:
        - ./local-dev.conf:/etc/service.conf
    ports:
        - "8000:80"

reg:
    image: abaco/core$TAG
    ports:
        - "5000:5000"
    volumes:
        - ./local-dev.conf:/etc/service.conf
        - ./abaco.log:/var/log/service.log
    environment:
        server: dev
        api: reg

mes:
    image: abaco/core$TAG
    volumes:
        - ./local-dev.conf:/etc/service.conf
        - ./abaco.log:/var/log/service.log
    ports:
        - "5001:5000"
    environment:
        server: dev
        api: mes

agavemes:
    image: abaco/core$TAG
    volumes:
        - ./local-dev.conf:/etc/service.conf
        - ./abaco.log:/var/log/service.log
    ports:
        - "5002:5000"
    environment:
        server: dev
        api: agavemes

admin:
    image: abaco/core$TAG
    volumes:
        - ./local-dev.conf:/etc/service.conf
        - ./abaco.log:/var/log/service.log
    ports:
        - "5003:5000"
    environment:
        server: dev
        api: admin

spawner:
    image: abaco/core$TAG
    command: "python3 -u /actors/spawner.py"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./local-dev.conf:/etc/service.conf
        - ./abaco.log:/var/log/service.log
    environment:
        abaco_conf_host_path: ${abaco_path}/local-dev.conf
        _abaco_secret: 123

clientg:
    image: abaco/core$TAG
    command: "python3 -u /actors/clients.py"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./local-dev.conf:/etc/service.conf
        - ./abaco.log:/var/log/service.log
    environment:
        abaco_conf_host_path: ${abaco_path}/local-dev.conf
        _abaco_secret: 123
        _abaco_AGAVE-PROD_username: abaco_service
        _abaco_AGAVE-PROD_password: changeme

health:
    image: abaco/core$TAG
    command: /actors/health_check.sh
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./local-dev.conf:/etc/service.conf
        - ./abaco.log:/var/log/service.log
