---

reg:
    image: ab_reg
    name: reg
    ports:
        - "5000:5000"
    links:
        - redis
        - rabbit


mes:
    image: ab_reg
    name: mes
    command: "python3 /actors/message_api.py"
    ports:
        - "5001:5000"
    links:
        - redis
        - rabbit

redis:
    image: redis
    name: redis
    ports:
        - "6379:6379"

rabbit:
    image: rabbitmq:3.5.3
    name: rabbit
    ports:
        - "5672:5672"
    environment:
        - RABBITMQ_NODENAME: abaco-rabbit

