---

nginx:
    image: jstubbs/abaco_nginx
    name: nginx
    volumes:
      - docs/swagger2.0.json:/docs/swagger2.0.json
    ports:
        - "8000:80"

reg:
    image: jstubbs/abaco_core
    name: reg
    ports:
        - "5000:5000"
    volumes:
        - ./abaco.conf:/etc/abaco.conf
    environment:
        server: gunicorn
        api: reg
    links:
        - redis
        - rabbit

mes:
    image: jstubbs/abaco_core
    name: mes
    ports:
        - "5001:5000"
    volumes:
        - ./abaco.conf:/etc/abaco.conf
    environment:
        server: gunicorn
        api: mes
    links:
        - redis
        - rabbit

admin:
    image: jstubbs/abaco_core
    name: admin
    ports:
        - "5003:5000"
    volumes:
        - ./abaco.conf:/etc/abaco.conf
    environment:
        server: gunicorn
        api: admin
    links:
        - redis
        - rabbit

spawner:
    image: jstubbs/abaco_core
    name: spawner
    command: "python3 -u /actors/spawner.py"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./abaco.conf:/etc/abaco.conf
    links:
        - redis
        - rabbit

health:
    image: jstubbs/abaco_core
    command: /actors/health_check.sh
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./abaco.conf:/etc/abaco.conf

redis:
    image: redis
    name: redis
    ports:
        - "6379:6379"
    command: redis-server --appendonly yes

rabbit:
    image: rabbitmq:3.5.3-management
    name: rabbit
    ports:
        - "5672:5672"
        - "15672:15672"
    environment:
       RABBITMQ_NODENAME: abaco-rabbit

