---

nginx:
    image: jstubbs/abaco_nginx
    name: nginx
    volumes:
        - ./local-dev.conf:/etc/abaco.conf
    ports:
        - "8000:80"

reg:
    image: jstubbs/abaco_core
    name: reg
    ports:
        - "5000:5000"
    volumes:
        - ./local-dev.conf:/etc/abaco.conf
    links:
        - redis
        - rabbit

mes:
    image: jstubbs/abaco_core
    name: mes
    command: "python3 -u /actors/message_api.py"
    volumes:
        - ./local-dev.conf:/etc/abaco.conf
    ports:
        - "5001:5000"
    links:
        - redis
        - rabbit

admin:
    image: jstubbs/abaco_core
    name: admin
    command: "python3 -u /actors/admin_api.py"
    volumes:
        - ./local-dev.conf:/etc/abaco.conf
    ports:
        - "5003:5000"
    links:
        - redis
        - rabbit

spawner:
    image: jstubbs/abaco_core
    name: spawner
    command: "python3 -u /actors/spawner.py"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    links:
        - redis
        - rabbit
health:
    image: jstubbs/abaco_core
    command: /actors/health_check.sh
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./local-dev.conf:/etc/abaco.conf

redis:
    image: redis
    name: redis
    ports:
        - "6379:6379"

rabbit:
    image: rabbitmq:3.5.3-management
    name: rabbit
    ports:
        - "5672:5672"
        - "15672:15672"
    environment:
       RABBITMQ_NODENAME: abaco-rabbit

