---

nginx:
    image: jstubbs/abaco_nginx
    volumes:
        - ./local-dev.conf:/etc/abaco.conf
    ports:
        - "8000:80"

reg:
    image: jstubbs/abaco_core
    ports:
        - "5000:5000"
    volumes:
        - ./local-dev.conf:/etc/abaco.conf
    environment:
        server: dev
        api: reg
    links:
        - redis
        - rabbit

mes:
    image: jstubbs/abaco_core
    volumes:
        - ./local-dev.conf:/etc/abaco.conf
    ports:
        - "5001:5000"
    environment:
        server: dev
        api: mes
    links:
        - redis
        - rabbit

admin:
    image: jstubbs/abaco_core
    volumes:
        - ./local-dev.conf:/etc/abaco.conf
    ports:
        - "5003:5000"
    environment:
        server: dev
        api: admin
    links:
        - redis
        - rabbit

spawner:
    image: jstubbs/abaco_core
    command: "python3 -u /actors/spawner.py"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./local-dev.conf:/etc/abaco.conf
    links:
        - redis
        - rabbit
    environment:
        - "abaco_conf_host_path=${abaco_path}/local-dev.conf"

health:
    image: jstubbs/abaco_core
    command: /actors/health_check.sh
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./local-dev.conf:/etc/abaco.conf

redis:
    image: redis
    ports:
        - "6379:6379"

rabbit:
    image: rabbitmq:3.5.3-management
    ports:
        - "5672:5672"
        - "15672:15672"
    environment:
       RABBITMQ_NODENAME: abaco-rabbit

