---

nginx:
    build: images/nginx
    name: nginx
    volumes:
      - docs/swagger2.0.json:/docs/swagger2.0.json
    ports:
        - "8000:80"

reg:
    build: .
    name: reg
    ports:
        - "5000:5000"
    links:
        - redis
        - rabbit

mes:
    build: .
    name: mes
    command: "python3 -u /actors/message_api.py"
    ports:
        - "5001:5000"
    links:
        - redis
        - rabbit

admin:
    build: .
    name: admin
    command: "python3 -u /actors/admin_api.py"
    ports:
        - "5003:5000"
    links:
        - redis
        - rabbit

spawner:
    build: .
    name: spawner
    command: "python3 -u /actors/spawner.py"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    links:
        - redis
        - rabbit
    environment:
          AE_IMAGE: abaco_spawner

redis:
    image: redis
    name: redis
    ports:
        - "6379:6379"

rabbit:
    image: rabbitmq:3.5.3-management
    name: rabbit
    ports:
        - "5672:5672"
        - "15672:15672"
    environment:
       RABBITMQ_NODENAME: abaco-rabbit

