---

reg:
    image: ab_reg
    name: reg
    ports:
        - "5000:5000"
    links:
        - redis

mes:
    image: ab_reg
    name: mes
    command: "python3 /actors/message_api.py"
    ports:
        - "5001:5000"
    links:
        - redis

redis:
    image: redis
    name: redis
    ports:
        - "6379:6379"
