---

- name: copy abaco.conf file
  copy: src={{ abaco_env }}/abaco.conf dest=/home/apim/abaco.conf
  sudo: yes
  sudo_user: "{{ linux_user }}"

- name: Compile docker_compose template
  template: src={{ abaco_env }}/docker-compose-compute.yml.j2 dest={{ base_dir }}/docker-compose-compute.yml
  sudo: yes
  sudo_user: "{{ linux_user }}"

- name: Compile pull_images template
  template: src=pull_images.sh.j2 dest=/home/apim/pull_images.sh
  sudo: yes
  sudo_user: "{{ linux_user }}"

- name: set permissions on pull_images.sh
  acl: permissions="rwx" name={{ base_dir }}/pull_images.sh state=present etype=user entity=apim
  sudo: yes

- name: Pull latest docker images
  shell: sh pull_images.sh chdir=/home/apim
  sudo: yes
  sudo_user: "{{ linux_user }}"

# ignore errors here since this call will fail if there are no containers running
- name: remove existing compute containers
  shell: docker-compose -f  docker-compose-compute.yml down
  sudo: yes
  sudo_user: "{{ linux_user }}"
  ignore_errors: yes

- name: start the containers with docker compose
  shell: docker-compose -f docker-compose-compute.yml up -d & chdir={{ base_dir }}
  sudo: yes
  sudo_user: "{{ linux_user }}"
  environment:
      COMPOSE_HTTP_TIMEOUT: 120
