# base directory to install abaco scripts and compose files.
base_dir: /home/apim

# user on remote host
linux_user: apim

# environment to deploy; one of 'staging' or 'prod'
abaco_env: prod

docker_user: abaco