---

spawner:
    name: spawner
    image: jstubbs/abaco_core
    command: "python3 -u /actors/spawner.py"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    environment:
        AE_IMAGE: jstubbs/abaco_core