---

nginx:
    image: jstubbs/abaco_nginx
    name: nginx
    ports:
        - "80:80"

reg:
    image: jstubbs/abaco_core
    name: reg
    ports:
        - "5000:5000"

mes:
    image: jstubbs/abaco_core
    name: mes
    command: "python3 -u /actors/message_api.py"
    ports:
        - "5001:5000"

admin:
    image: jstubbs/abaco_core
    name: admin
    command: "python3 -u /actors/admin_api.py"
    ports:
        - "5003:5000"
